#!/bin/bash

FNAME=$1

if [[ -z "$FNAME" ]]; then
    echo "decrypt <name of file>"
    echo "  - decrypt is a script to decrypt des3 encrypted files"
    exit;
fi

openssl des3 -d -salt -in "$FNAME" -out "${FNAME%.[^.]*}"
rm -f $FNAME

